### Products Show
GET http://localhost:3000/products/1

### Products Index
GET http://localhost:3000/products.json?category=

### Products Create
POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Nzg4MzgzNDJ9.ATu3FIfSFKVQZWevLOOCPqrvCaIJScjw70AVs5DHExE
Content-Type: application/json

{
  "name":"diet tropic thunder",
  "price":3,
  "image_url":"https://images.unsplash.com/photo-1655604646151-8edc8746bb01?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZnJlc2NhfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  "description": "light purple stuff",
  "supplier_id": "1",
  "inventory": 2
}

### Products Update
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{
  "price": 7
}

### Products Destroy
DELETE http://localhost:3000/products/1.json


### User Create (aka Signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Jamaal",
  "email": "jamaal@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Session Create (aka Login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jamaal@test.com",
  "password": "password"
}

### Orders Create
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzkzMzE3OTN9.gMAAxIXy18dyq7rItVsm1iDGnZ-81I0wy93CgOLWeU4
Content-Type: application/json

{
  "product_id":1,
  "quantity":2
}

### Orders Show
GET http://localhost:3000/orders/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzkwMDk4MDF9.f3oWm92iMsiMf8yXLa-3tcVS7-n-VBCCfHOJWHx2gRI

### Orders Index
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzkwMDk4MDF9.f3oWm92iMsiMf8yXLa-3tcVS7-n-VBCCfHOJWHx2gRI

### Carted Products Create
POST http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzkzMzE3OTN9.gMAAxIXy18dyq7rItVsm1iDGnZ-81I0wy93CgOLWeU4
Content-Type: application/json

{
"product_id": 1,
"quantity": 1
}

### Carted Products Index
GET http://localhost:3000/carted_products.json
Authorization: 